--- 
version: "2.1" 

networks:
#  vpn-network:
#    name: vpn-network
  jellyfin-network:
    name: jellyfin-network

volumes:
  portainer-data:
  jellyfin-config:
  jellyseerr-config:
  nzbget-config:
  sonarr-config:
  radarr-config:
  lidarr-config:
  ombi-config:
  
services: 
  portainer:
    image: portainer/portainer
    container_name: portainer 
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  jellyfin: 
    image: lscr.io/linuxserver/jellyfin:latest 
    container_name: jellyfin
    networks:
      - jellyfin-network
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=America/New_York 
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional 
    volumes: 
      - jellyfin-config:/config 
      - /mnt/media/tv:/data/tvshows 
      - /mnt/media/movies:/data/movies 
      - /mnt/media/music:/data/music
      - /mnt/transcodes:/transcodes
    ports: 
      - 8096:8096 
      #- 8920:8920 #optional 
      #- 7359:7359/udp #optional 
      #- 1900:1900/udp #optional 
    restart: unless-stopped 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-config:/app/config
    restart: unless-stopped

  nzbget: 
    image: lscr.io/linuxserver/nzbget:latest 
    container_name: nzbget
#    network_mode: service:openvpn
    networks:
      - jellyfin-network
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=America/New_York 
      - NZBGET_USER=nzbget #optional 
      - NZBGET_PASS=tegbzn6789 #optional 
    volumes: 
      - nzbget-config:/config 
      - /mnt/media/downloads:/downloads #optional 
    ports: # commented out if using a different network
      - 6789:6789 
    restart: unless-stopped 

  sonarr: 
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=America/New_York 
    volumes: 
      - sonarr-config:/config 
      - /mnt/media/tv:/tv #optional 
      - /mnt/media/downloads:/downloads #optional 
    ports: 
      - 8989:8989 
    restart: unless-stopped 

  radarr: 
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=America/New_York 
    volumes: 
      - radarr-config:/config 
      - /mnt/media/movies:/movies #optional 
      - /mnt/media/downloads:/downloads #optional 
    ports: 
      - 7878:7878 
    restart: unless-stopped 

  lidarr: 
    image: lscr.io/linuxserver/lidarr:latest 
    container_name: lidarr 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=America/New_York 
    volumes: 
      - lidarr-config:/config 
      - /mnt/media/music:/music #optional 
      - /mnt/media/downloads:/downloads #optional 
    ports: 
      - 8686:8686 
    restart: unless-stopped 
